apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: licensingservice
  name: licensingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: licensingservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: licensingservice
    spec:
      containers:
        - env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver:8071
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: 072085842419.dkr.ecr.eu-west-1.amazonaws.com/ostock/licensing-service:0.0.1
          name: licensingservice
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
